### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielpaul**

### CODE REVIEW

**Comment by skakri** [comment]
Is this really needed? I have no issues with current setup.

**Comment by danielpaul** [comment]
@skakri I had to do this to get it working on Rails 4.

**Comment by skakri** [comment]
I have no issues with Rails 4.2.1; maybe you have some error logs or some other information about your setup that may help?

mc5rcqv

**Comment by skakri** [comment]
Closing due to inactivity.

**Pull request closed without merging**
